
pipeline {
  agent any

  environment {
    REGISTRY = "my-jenkins-server:5000"
    IMAGE_NAME = "user-service"
  }

  stages {
    stage('Checkout') {
      steps {
        git 'https://github.com/<username>/user-service.git'
      }
    }

    stage('Build Image') {
      steps {
        sh "docker build -t $REGISTRY/$IMAGE_NAME:latest ."
      }
    }

    stage('Push Image') {
      steps {
        sh "docker push $REGISTRY/$IMAGE_NAME:latest"
      }
    }

    stage('Deploy to K8s') {
      steps {
        sh "kubectl apply -f deployment.yaml"
        sh "kubectl apply -f service.yaml"
      }
    }
  }
}
